/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type TimelineEntry = {
  _id: string
  _type: 'timelineEntry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  kind?: 'work' | 'education'
  organisation?: string
  role?: string
  startDate?: string
  endDate?: string
  isCurrent?: boolean
  location?: string
  summary?: string
  highlights?: Array<string>
  relatedProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  result?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  order?: number
  blurb?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  role?: string
  year?: string
  engine?: 'Unity' | 'Unreal' | 'Godot' | 'Custom' | 'Other'
  tech?: Array<string>
  platforms?: Array<string>
  cover?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  videoUrl?: string
  links?: Array<{
    label?: string
    url?: string
    _type: 'projectLink'
    _key: string
  }>
  teamSize?: number
  featured?: boolean
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SocialLink = {
  _id: string
  _type: 'socialLink'
  _createdAt: string
  _updatedAt: string
  _rev: string
  platform?: 'itch' | 'github' | 'twitter' | 'linkedin'
  url?: string
  buttonSlot?: 'A' | 'B' | 'X' | 'Y'
  label?: string
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fullName?: string
  title?: string
  statusLine?: string
  aboutHeadline?: string
  aboutBody?: string
  resumeFile?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  resumeLabel?: string
  avatar?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  seo?: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ProjectReference
  | SanityImageAssetReference
  | TimelineEntry
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | SocialLink
  | SanityFileAssetReference
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  fullName,  title,  statusLine,  aboutHeadline,  aboutBody,  resumeLabel,  "resumeUrl": resumeFile.asset->url,  seo}
export type SiteSettingsQueryResult = {
  fullName: string | null
  title: string | null
  statusLine: string | null
  aboutHeadline: string | null
  aboutBody: string | null
  resumeLabel: string | null
  resumeUrl: string | null
  seo: {
    metaTitle?: string
    metaDescription?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: socialLinksQuery
// Query: *[_type == "socialLink"] | order(buttonSlot asc){  _id,  platform,  url,  buttonSlot,  label}
export type SocialLinksQueryResult = Array<{
  _id: string
  platform: 'github' | 'itch' | 'linkedin' | 'twitter' | null
  url: string | null
  buttonSlot: 'A' | 'B' | 'X' | 'Y' | null
  label: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(order asc){  _id,  title,  "slug": slug.current,  order,  blurb,  description,  role,  year,  engine,  tech,  platforms,  cover,  gallery,  videoUrl,  links[]{label, url},  teamSize,  featured}
export type ProjectsQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  order: number | null
  blurb: string | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  role: string | null
  year: string | null
  engine: 'Custom' | 'Godot' | 'Other' | 'Unity' | 'Unreal' | null
  tech: Array<string> | null
  platforms: Array<string> | null
  cover: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  gallery: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }> | null
  videoUrl: string | null
  links: Array<{
    label: string | null
    url: string | null
  }> | null
  teamSize: number | null
  featured: boolean | null
}>

// Source: sanity/lib/queries.ts
// Variable: timelineQuery
// Query: *[_type == "timelineEntry"] | order(select(kind == "work" => 0, 1) asc, startDate desc){  _id,  kind,  organisation,  role,  startDate,  endDate,  isCurrent,  location,  summary,  highlights,  result,  relatedProjects[]->{_id, title, "slug": slug.current}}
export type TimelineQueryResult = Array<{
  _id: string
  kind: 'education' | 'work' | null
  organisation: string | null
  role: string | null
  startDate: string | null
  endDate: string | null
  isCurrent: boolean | null
  location: string | null
  summary: string | null
  highlights: Array<string> | null
  result: string | null
  relatedProjects: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  fullName,\n  title,\n  statusLine,\n  aboutHeadline,\n  aboutBody,\n  resumeLabel,\n  "resumeUrl": resumeFile.asset->url,\n  seo\n}': SiteSettingsQueryResult
    '*[_type == "socialLink"] | order(buttonSlot asc){\n  _id,\n  platform,\n  url,\n  buttonSlot,\n  label\n}': SocialLinksQueryResult
    '*[_type == "project"] | order(order asc){\n  _id,\n  title,\n  "slug": slug.current,\n  order,\n  blurb,\n  description,\n  role,\n  year,\n  engine,\n  tech,\n  platforms,\n  cover,\n  gallery,\n  videoUrl,\n  links[]{label, url},\n  teamSize,\n  featured\n}': ProjectsQueryResult
    '*[_type == "timelineEntry"] | order(select(kind == "work" => 0, 1) asc, startDate desc){\n  _id,\n  kind,\n  organisation,\n  role,\n  startDate,\n  endDate,\n  isCurrent,\n  location,\n  summary,\n  highlights,\n  result,\n  relatedProjects[]->{_id, title, "slug": slug.current}\n}': TimelineQueryResult
  }
}
